"""fase5: homebrew/criado_por em referencias + mesa_fontes_aceitas

Revision ID: 0ba57e6c8e18
Revises: e8c592ad9299
Create Date: 2026-06-06 11:41:11.166366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ba57e6c8e18'
down_revision = 'e8c592ad9299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesa_fontes_aceitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=False),
    sa.Column('fonte', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], name=op.f('fk_mesa_fontes_aceitas_mesa_id_mesas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mesa_fontes_aceitas')),
    sa.UniqueConstraint('mesa_id', 'fonte', name='uq_mesa_fonte')
    )
    with op.batch_alter_table('mesa_fontes_aceitas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mesa_fontes_aceitas_mesa_id'), ['mesa_id'], unique=False)

    with op.batch_alter_table('antecedentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homebrew', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('criado_por', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_antecedentes_criado_por_users'), 'users', ['criado_por'], ['id'])

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homebrew', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('criado_por', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_classes_criado_por_users'), 'users', ['criado_por'], ['id'])

    with op.batch_alter_table('magias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homebrew', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('criado_por', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_magias_criado_por_users'), 'users', ['criado_por'], ['id'])

    with op.batch_alter_table('racas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homebrew', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('criado_por', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_racas_criado_por_users'), 'users', ['criado_por'], ['id'])

    with op.batch_alter_table('talentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('homebrew', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('criado_por', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_talentos_criado_por_users'), 'users', ['criado_por'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talentos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_talentos_criado_por_users'), type_='foreignkey')
        batch_op.drop_column('criado_por')
        batch_op.drop_column('homebrew')

    with op.batch_alter_table('racas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_racas_criado_por_users'), type_='foreignkey')
        batch_op.drop_column('criado_por')
        batch_op.drop_column('homebrew')

    with op.batch_alter_table('magias', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_magias_criado_por_users'), type_='foreignkey')
        batch_op.drop_column('criado_por')
        batch_op.drop_column('homebrew')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_classes_criado_por_users'), type_='foreignkey')
        batch_op.drop_column('criado_por')
        batch_op.drop_column('homebrew')

    with op.batch_alter_table('antecedentes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_antecedentes_criado_por_users'), type_='foreignkey')
        batch_op.drop_column('criado_por')
        batch_op.drop_column('homebrew')

    with op.batch_alter_table('mesa_fontes_aceitas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mesa_fontes_aceitas_mesa_id'))

    op.drop_table('mesa_fontes_aceitas')
    # ### end Alembic commands ###
