"""enriquecimento: efeitos (ref) + talentos/ca_ajuste (personagem)

Revision ID: 14082adb24ce
Revises: 9bbb44681dea
Create Date: 2026-06-06 10:52:22.999113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14082adb24ce'
down_revision = '9bbb44681dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('antecedentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('efeitos', sa.JSON(), nullable=True))

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('efeitos', sa.JSON(), nullable=True))

    with op.batch_alter_table('personagens', schema=None) as batch_op:
        # server_default='0' garante valor em linhas existentes (NOT NULL sem quebrar).
        batch_op.add_column(sa.Column('ca_ajuste', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('talentos', sa.JSON(), nullable=True))

    with op.batch_alter_table('racas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('efeitos', sa.JSON(), nullable=True))

    with op.batch_alter_table('talentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('efeitos', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talentos', schema=None) as batch_op:
        batch_op.drop_column('efeitos')

    with op.batch_alter_table('racas', schema=None) as batch_op:
        batch_op.drop_column('efeitos')

    with op.batch_alter_table('personagens', schema=None) as batch_op:
        batch_op.drop_column('talentos')
        batch_op.drop_column('ca_ajuste')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('efeitos')

    with op.batch_alter_table('antecedentes', schema=None) as batch_op:
        batch_op.drop_column('efeitos')

    # ### end Alembic commands ###
