"""e20: campos de identidade e simbolo_faccao no personagem

Revision ID: 18f5cd8545e6
Revises: f3fb253e632d
Create Date: 2026-06-06 16:30:09.587061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f5cd8545e6'
down_revision = 'f3fb253e632d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idade', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('altura', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('peso', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('olhos', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('pele', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('cabelo', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('faccao', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('aparencia', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('aliados', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tesouro', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('simbolo_faccao_url', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personagens', schema=None) as batch_op:
        batch_op.drop_column('simbolo_faccao_url')
        batch_op.drop_column('tesouro')
        batch_op.drop_column('aliados')
        batch_op.drop_column('aparencia')
        batch_op.drop_column('faccao')
        batch_op.drop_column('cabelo')
        batch_op.drop_column('pele')
        batch_op.drop_column('olhos')
        batch_op.drop_column('peso')
        batch_op.drop_column('altura')
        batch_op.drop_column('idade')

    # ### end Alembic commands ###
