"""e22: tracos_extras no personagem (traços/recursos incrementais)

Revision ID: 7ed254ff640a
Revises: 18f5cd8545e6
Create Date: 2026-06-06 19:31:08.051448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed254ff640a'
down_revision = '18f5cd8545e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracos_extras', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personagens', schema=None) as batch_op:
        batch_op.drop_column('tracos_extras')

    # ### end Alembic commands ###
