"""baseline schema inicial

Revision ID: 9bbb44681dea
Revises: 
Create Date: 2026-06-06 09:10:04.021444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bbb44681dea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antecedentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('pericias', sa.JSON(), nullable=True),
    sa.Column('idiomas', sa.Integer(), nullable=True),
    sa.Column('equipamento', sa.Text(), nullable=True),
    sa.Column('fonte', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('antecedentes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_antecedentes_fonte'), ['fonte'], unique=False)
        batch_op.create_index(batch_op.f('ix_antecedentes_slug'), ['slug'], unique=True)

    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('dado_vida', sa.Integer(), nullable=True),
    sa.Column('atributo_principal', sa.JSON(), nullable=True),
    sa.Column('salvaguardas', sa.JSON(), nullable=True),
    sa.Column('pericias_disponiveis', sa.JSON(), nullable=True),
    sa.Column('num_pericias', sa.Integer(), nullable=True),
    sa.Column('conjurador', sa.Boolean(), nullable=True),
    sa.Column('atributo_conjuracao', sa.String(length=3), nullable=True),
    sa.Column('proficiencias_armadura', sa.JSON(), nullable=True),
    sa.Column('proficiencias_arma', sa.JSON(), nullable=True),
    sa.Column('fonte', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_fonte'), ['fonte'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_slug'), ['slug'], unique=True)

    op.create_table('magias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=True),
    sa.Column('escola', sa.String(length=40), nullable=True),
    sa.Column('tempo_conjuracao', sa.String(length=60), nullable=True),
    sa.Column('alcance', sa.String(length=60), nullable=True),
    sa.Column('componentes', sa.String(length=60), nullable=True),
    sa.Column('duracao', sa.String(length=60), nullable=True),
    sa.Column('concentracao', sa.Boolean(), nullable=True),
    sa.Column('ritual', sa.Boolean(), nullable=True),
    sa.Column('classes', sa.JSON(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('fonte', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('magias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_magias_fonte'), ['fonte'], unique=False)
        batch_op.create_index(batch_op.f('ix_magias_nivel'), ['nivel'], unique=False)
        batch_op.create_index(batch_op.f('ix_magias_slug'), ['slug'], unique=True)

    op.create_table('racas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('deslocamento', sa.Integer(), nullable=True),
    sa.Column('tamanho', sa.String(length=30), nullable=True),
    sa.Column('bonus_atributos', sa.JSON(), nullable=True),
    sa.Column('tracos', sa.JSON(), nullable=True),
    sa.Column('subracas', sa.JSON(), nullable=True),
    sa.Column('fonte', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('racas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_racas_fonte'), ['fonte'], unique=False)
        batch_op.create_index(batch_op.f('ix_racas_slug'), ['slug'], unique=True)

    op.create_table('talentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('pre_requisito', sa.String(length=160), nullable=True),
    sa.Column('fonte', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('talentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_talentos_fonte'), ['fonte'], unique=False)
        batch_op.create_index(batch_op.f('ix_talentos_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('mesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('sistema', sa.String(length=60), nullable=False),
    sa.Column('codigo_convite', sa.String(length=8), nullable=False),
    sa.Column('mestre_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mestre_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mesas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mesas_codigo_convite'), ['codigo_convite'], unique=True)
        batch_op.create_index(batch_op.f('ix_mesas_mestre_id'), ['mestre_id'], unique=False)

    op.create_table('membros_mesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('papel_na_mesa', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mesa_id', 'user_id', name='uq_membro_mesa')
    )
    op.create_table('monstros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=60), nullable=True),
    sa.Column('tamanho', sa.String(length=30), nullable=True),
    sa.Column('alinhamento', sa.String(length=60), nullable=True),
    sa.Column('ca', sa.Integer(), nullable=False),
    sa.Column('pv', sa.Integer(), nullable=False),
    sa.Column('pv_formula', sa.String(length=40), nullable=True),
    sa.Column('deslocamento', sa.String(length=60), nullable=True),
    sa.Column('atributos', sa.JSON(), nullable=True),
    sa.Column('nd', sa.String(length=10), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('pericias', sa.Text(), nullable=True),
    sa.Column('sentidos', sa.Text(), nullable=True),
    sa.Column('idiomas', sa.Text(), nullable=True),
    sa.Column('habilidades', sa.JSON(), nullable=True),
    sa.Column('acoes', sa.JSON(), nullable=True),
    sa.Column('is_pdm', sa.Boolean(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('fonte', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monstros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monstros_fonte'), ['fonte'], unique=False)
        batch_op.create_index(batch_op.f('ix_monstros_mesa_id'), ['mesa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_monstros_slug'), ['slug'], unique=False)

    op.create_table('personagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('nome_jogador', sa.String(length=120), nullable=True),
    sa.Column('raca_slug', sa.String(length=60), nullable=True),
    sa.Column('classe_slug', sa.String(length=60), nullable=True),
    sa.Column('antecedente_slug', sa.String(length=60), nullable=True),
    sa.Column('tendencia', sa.String(length=40), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('forca', sa.Integer(), nullable=False),
    sa.Column('destreza', sa.Integer(), nullable=False),
    sa.Column('constituicao', sa.Integer(), nullable=False),
    sa.Column('inteligencia', sa.Integer(), nullable=False),
    sa.Column('sabedoria', sa.Integer(), nullable=False),
    sa.Column('carisma', sa.Integer(), nullable=False),
    sa.Column('ca', sa.Integer(), nullable=False),
    sa.Column('iniciativa_bonus', sa.Integer(), nullable=False),
    sa.Column('deslocamento', sa.String(length=20), nullable=True),
    sa.Column('pv_max', sa.Integer(), nullable=False),
    sa.Column('pv_atual', sa.Integer(), nullable=False),
    sa.Column('pv_temp', sa.Integer(), nullable=False),
    sa.Column('dado_vida', sa.String(length=20), nullable=True),
    sa.Column('inspiracao', sa.Boolean(), nullable=False),
    sa.Column('pericias_proficientes', sa.JSON(), nullable=True),
    sa.Column('salvaguardas_proficientes', sa.JSON(), nullable=True),
    sa.Column('outras_proficiencias', sa.Text(), nullable=True),
    sa.Column('classe_conjuradora', sa.String(length=60), nullable=True),
    sa.Column('atributo_conjuracao', sa.String(length=3), nullable=True),
    sa.Column('truques', sa.JSON(), nullable=True),
    sa.Column('magias', sa.JSON(), nullable=True),
    sa.Column('tracos_personalidade', sa.Text(), nullable=True),
    sa.Column('ideais', sa.Text(), nullable=True),
    sa.Column('vinculos', sa.Text(), nullable=True),
    sa.Column('fraquezas', sa.Text(), nullable=True),
    sa.Column('historia', sa.Text(), nullable=True),
    sa.Column('caracteristicas', sa.Text(), nullable=True),
    sa.Column('idiomas', sa.Text(), nullable=True),
    sa.Column('equipamento', sa.Text(), nullable=True),
    sa.Column('ataques', sa.Text(), nullable=True),
    sa.Column('dinheiro', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personagens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personagens_mesa_id'), ['mesa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_personagens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personagens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personagens_user_id'))
        batch_op.drop_index(batch_op.f('ix_personagens_mesa_id'))

    op.drop_table('personagens')
    with op.batch_alter_table('monstros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monstros_slug'))
        batch_op.drop_index(batch_op.f('ix_monstros_mesa_id'))
        batch_op.drop_index(batch_op.f('ix_monstros_fonte'))

    op.drop_table('monstros')
    op.drop_table('membros_mesa')
    with op.batch_alter_table('mesas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mesas_mestre_id'))
        batch_op.drop_index(batch_op.f('ix_mesas_codigo_convite'))

    op.drop_table('mesas')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('talentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_talentos_slug'))
        batch_op.drop_index(batch_op.f('ix_talentos_fonte'))

    op.drop_table('talentos')
    with op.batch_alter_table('racas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_racas_slug'))
        batch_op.drop_index(batch_op.f('ix_racas_fonte'))

    op.drop_table('racas')
    with op.batch_alter_table('magias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_magias_slug'))
        batch_op.drop_index(batch_op.f('ix_magias_nivel'))
        batch_op.drop_index(batch_op.f('ix_magias_fonte'))

    op.drop_table('magias')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_slug'))
        batch_op.drop_index(batch_op.f('ix_classes_fonte'))

    op.drop_table('classes')
    with op.batch_alter_table('antecedentes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_antecedentes_slug'))
        batch_op.drop_index(batch_op.f('ix_antecedentes_fonte'))

    op.drop_table('antecedentes')
    # ### end Alembic commands ###
