"""fase2: tabelas armas, armaduras, itens

Revision ID: 9c6b8cab1404
Revises: 14082adb24ce
Create Date: 2026-06-06 11:23:15.549555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6b8cab1404'
down_revision = '14082adb24ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('armaduras',
    sa.Column('categoria', sa.String(length=40), nullable=True),
    sa.Column('ca_base', sa.Integer(), nullable=True),
    sa.Column('ca_soma_des', sa.Boolean(), nullable=True),
    sa.Column('ca_des_max', sa.Integer(), nullable=True),
    sa.Column('ca_bonus', sa.Integer(), nullable=True),
    sa.Column('requisito_forca', sa.Integer(), nullable=True),
    sa.Column('furtividade_desvantagem', sa.Boolean(), nullable=True),
    sa.Column('bonus_magico', sa.Integer(), nullable=True),
    sa.Column('efeitos', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=90), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('fonte', sa.String(length=120), nullable=False),
    sa.Column('homebrew', sa.Boolean(), nullable=False),
    sa.Column('idioma', sa.String(length=2), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('personagem_id', sa.Integer(), nullable=True),
    sa.Column('mesa_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ),
    sa.ForeignKeyConstraint(['personagem_id'], ['personagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('armaduras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_armaduras_mesa_id'), ['mesa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_armaduras_personagem_id'), ['personagem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_armaduras_slug'), ['slug'], unique=False)

    op.create_table('armas',
    sa.Column('categoria', sa.String(length=40), nullable=True),
    sa.Column('alcance', sa.String(length=40), nullable=True),
    sa.Column('dano', sa.String(length=40), nullable=True),
    sa.Column('tipo_dano', sa.String(length=40), nullable=True),
    sa.Column('propriedades', sa.JSON(), nullable=True),
    sa.Column('bonus_magico', sa.Integer(), nullable=True),
    sa.Column('efeitos', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=90), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('fonte', sa.String(length=120), nullable=False),
    sa.Column('homebrew', sa.Boolean(), nullable=False),
    sa.Column('idioma', sa.String(length=2), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('personagem_id', sa.Integer(), nullable=True),
    sa.Column('mesa_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ),
    sa.ForeignKeyConstraint(['personagem_id'], ['personagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('armas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_armas_mesa_id'), ['mesa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_armas_personagem_id'), ['personagem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_armas_slug'), ['slug'], unique=False)

    op.create_table('itens',
    sa.Column('tipo_item', sa.String(length=60), nullable=True),
    sa.Column('raridade', sa.String(length=40), nullable=True),
    sa.Column('requer_sintonia', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=90), nullable=True),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('fonte', sa.String(length=120), nullable=False),
    sa.Column('homebrew', sa.Boolean(), nullable=False),
    sa.Column('idioma', sa.String(length=2), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('personagem_id', sa.Integer(), nullable=True),
    sa.Column('mesa_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ),
    sa.ForeignKeyConstraint(['personagem_id'], ['personagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_mesa_id'), ['mesa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_personagem_id'), ['personagem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_slug'), ['slug'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_slug'))
        batch_op.drop_index(batch_op.f('ix_itens_personagem_id'))
        batch_op.drop_index(batch_op.f('ix_itens_mesa_id'))

    op.drop_table('itens')
    with op.batch_alter_table('armas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_armas_slug'))
        batch_op.drop_index(batch_op.f('ix_armas_personagem_id'))
        batch_op.drop_index(batch_op.f('ix_armas_mesa_id'))

    op.drop_table('armas')
    with op.batch_alter_table('armaduras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_armaduras_slug'))
        batch_op.drop_index(batch_op.f('ix_armaduras_personagem_id'))
        batch_op.drop_index(batch_op.f('ix_armaduras_mesa_id'))

    op.drop_table('armaduras')
    # ### end Alembic commands ###
