"""fase3: equipamento do personagem (armadura_equipada_id, armas_equipadas)

Revision ID: e8c592ad9299
Revises: 9c6b8cab1404
Create Date: 2026-06-06 11:28:33.033174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c592ad9299'
down_revision = '9c6b8cab1404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('armadura_equipada_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('armas_equipadas', sa.JSON(), nullable=True))
        batch_op.create_foreign_key(None, 'armaduras', ['armadura_equipada_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personagens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('armas_equipadas')
        batch_op.drop_column('armadura_equipada_id')

    # ### end Alembic commands ###
