"""fase6: cache de traducoes

Revision ID: f3fb253e632d
Revises: 0ba57e6c8e18
Create Date: 2026-06-06 11:47:00.403930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3fb253e632d'
down_revision = '0ba57e6c8e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traducoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('slug', sa.String(length=90), nullable=False),
    sa.Column('campo', sa.String(length=30), nullable=False),
    sa.Column('idioma', sa.String(length=2), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_traducoes')),
    sa.UniqueConstraint('tipo', 'slug', 'campo', 'idioma', name='uq_traducao')
    )
    with op.batch_alter_table('traducoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traducoes_slug'), ['slug'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traducoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traducoes_slug'))

    op.drop_table('traducoes')
    # ### end Alembic commands ###
